In [1]:
import pandas as pd
from covid_model_parametrization.utils import utils
from covid_model_parametrization.config import Config

In [2]:
df_covid = pd.read_csv('Inputs/BRA/COVID/covid_data.csv',header=0,skiprows=0,sep=";")
df_covid=df_covid.drop_duplicates()

In [ ]:
df_covid.columns

In [ ]:
df_covid.shape

In [ ]:
df_covid.head()

In [ ]:
null_df = df_covid[df_covid['codmun'].notnull() & df_covid['municipio'].notnull()]
new_df = df_covid.dropna(subset=['municipio','codmun'])
null_df['codmun'].isnull()

In [ ]:
list(df_covid['estado'].unique())

In [ ]:
len(list(df_covid['municipio'].unique()))

In [ ]:
import geopandas as gpd

exposure_gdf = gpd.read_file('Outputs/BRA/Exposure_SADD/BRA_Exposure.geojson')

In [ ]:
exposure_gdf.head()

In [ ]:
def get_dict_pcodes(exposure, adm_unit_name, adm_unit_pcode="ADM1_PCODE"):
    pcode_dict = dict()
    for k, v in exposure.groupby(adm_unit_name):
        pcode_dict[k] = v.iloc[0, :][adm_unit_pcode]
    return pcode_dict

ADM2_ADM1_pcodes = get_dict_pcodes(exposure_gdf, "ADM2_PCODE")

In [ ]:
ADM2_names = get_dict_pcodes(
            exposure_gdf, "ADM2_PT", "ADM2_PCODE"
        )

In [ ]:
from hdx.utilities.easy_logging import setup_logging
from hdx.hdx_configuration import Configuration
from hdx.data.dataset import Dataset
Configuration.create(hdx_site='prod', user_agent='jaredrossj', hdx_read_only=True)

In [ ]:
dataset = Dataset.read_from_hdx('acled-conflict-data-for-africa-1997-lastyear')
print(dataset.get_dataset_date())

In [ ]:
dataset = Dataset.read_from_hdx("hotosm_ita_roads")

In [ ]:
from hdx.location.country import Country

Country.get_iso2_from_iso3('bra')

In [3]:
from covid_model_parametrization.config import Config

config = Config()
parameters = config.parameters("bra")
df_covid=df_covid.drop_duplicates()
df_covid = df_covid.rename(columns=parameters["covid"]["hlx_dict"])
df_covid = df_covid[df_covid[config.HLX_TAG_ADM2_PCODE].notnull() & df_covid[config.HLX_TAG_ADM2_NAME] != 0]

In [5]:
df_covid[df_covid["#adm1+pcode"].isin([11,12,13,14,15])]

,regiao,#adm1+name,#adm2+name,#adm1+pcode,#adm2+pcode,codRegiaoSaude,nomeRegiaoSaude,#date,semanaEpi,populacaoTCU2019,#affected+infected+confirmed+total,casosNovos,#affected+infected+dead+total,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
8350,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-27,13,22945.0,0,0,0,0,NaN,NaN,0.0
8351,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-28,13,22945.0,0,0,0,0,NaN,NaN,0.0
8352,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-29,14,22945.0,0,0,0,0,NaN,NaN,0.0
8353,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-30,14,22945.0,0,0,0,0,NaN,NaN,0.0
8354,Norte,RO,Alta Floresta D'Oeste,11,110001.0,11005.0,ZONA DA MATA,2020-03-31,14,22945.0,0,0,0,0,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84713,Norte,PA,Xinguara,15,150840.0,15001.0,ARAGUAIA,2020-12-05,49,44751.0,2667,0,26,0,NaN,NaN,0.0
84714,Norte,PA,Xinguara,15,150840.0,15001.0,ARAGUAIA,2020-12-06,50,44751.0,2667,0,26,0,NaN,NaN,0.0
84715,Norte,PA,Xinguara,15,150840.0,15001.0,ARAGUAIA,2020-12-07,50,44751.0,2667,0,26,0,NaN,NaN,0.0
84716,Norte,PA,Xinguara,15,150840.0,15001.0,ARAGUAIA,2020-12-08,50,44751.0,2667,0,26,0,NaN,NaN,0.0
84717,Norte,PA,Xinguara,15,150840.0,15001.0,ARAGUAIA,2020-12-09,50,44751.0,2667,0,26,0,NaN,NaN,0.0

In [4]:
df_covid[df_covid["#adm1+pcode"].isin([11,12,13,14,15])].to_csv('BR_covid.csv')

In [ ]:
df = pd.read_csv('2010-2019_Panel_data_20201201.csv')
list(df.columns)

In [ ]:
df[df['fips'] == 1001]

In [ ]:
from datetime import date, timedelta
series = []
startDate = date(2020,1,22)
for i in range(0,90):
    series.append({
        'name':(startDate+timedelta(days=i)).strftime('%-m/%-d/%y'),
        'value':1
    })
for i,d in enumerate(data):
    newDate = startDate+timedelta(days=i+90)
    series.append({
        'name':(newDate).strftime('%-m/%-d/%y'),
        'value':d
    })
for i in range(0,47):
    series.append({
        'name':(newDate+timedelta(days=i)).strftime('%-m/%-d/%y'),
        'value':1
    })

[{'name':'Rt Values','series':series,}]

In [3]:
import os
import geopandas as gpd

from covid_model_parametrization.config import Config
from covid_model_parametrization.utils import utils
import importlib
importlib.reload(utils)
config = Config()
parameters = config.parameters('ITA')
input_dir = os.path.join(config.DIR_PATH, config.INPUT_DIR, 'ITA')
ADM2boundaries = utils.read_in_admin_boundaries(config, parameters, 'ITA')

{'admin': {'directory': 'ProvCM01012020', 'language': 'IT', 'references': ['Reg01012020', 'RipGeo01012020'], 'adm_renames': {'COD_RIP': 'ADM0_PCODE', 'COD_REG': 'ADM1_PCODE', 'COD_PROV': 'ADM2_PCODE', 'DEN_UTS': 'ADM2_IT', 'DEN_REG': 'ADM1_IT', 'DEN_RIP': 'ADM0_IT'}}, 'mobility': {'file': 'roads.shp', 'scaling_factor': {'household_size': 2.4, 'motor_vehicle_fraction': 0.734}}, 'vulnerability': {'ghs': {'column_row_pairs': ['(18, 3)', '(18, 4)', '(19, 3)', '(19, 4)']}, 'ipc': {'filename': None}, 'solid_fuels': {'frac_urban': 0.02, 'frac_rural': 0.02}, 'handwashing_facilities': {'frac_urban': 0.05, 'frac_rural': 0.1}, 'raised_blood_pressure': 0.38, 'diabetes': 0.053, 'smoking': 0.19}, 'covid': {'url': 'https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json', 'filename': 'dpc-covid19-ita-regioni.json', 'filtype': 'json', 'header': 0, 'skiprows': 0, 'cases': None, 'deaths': None, 'individual_case_data': None, 'cumulative': None, 'admin_level': None, 'federal_state_dict': None, 'adm1_name_exp': None, 'adm2_name_exp': None, 'date_format': None, 'replace_dict': {'old_name': None}, 'hlx_dict': {'#old_hxl_name': None}}, 'contact_matrix': {'country': 'Italy', 'file_number': 1}, 'NPIs': {'url': None}}
ITA

In [ ]:
ADM2boundaries

In [ ]:
import logging
import rasterio
from rasterio.mask import mask
country_iso3='ITA'

logger = logging.getLogger(__name__)

gender_age_group_name = "f_20"
logger.info(f"analyising gender age {gender_age_group_name}")
input_tiff_file = os.path.join(
    input_dir,
    config.WORLDPOP_DIR,
    config.WORLDPOP_FILENAMES["sadd"].format(
        country_iso3=country_iso3.lower(),
        gender="f",
        age="20",
    ),
)
raster = rasterio.open(input_tiff_file)
ADM2boundaries[gender_age_group_name] = (
    ADM2boundaries['geometry'].apply(lambda x: mask(raster, [x], crop=True, nodata=0)[0].sum()))

In [ ]:
parameters["admin"]["Test"]

In [20]:
from datetime import datetime

datetime.strptime("2020-02-24T18:00:00","%Y-%m-%dT%H:%M:%S").day

24

In [10]:
country_iso3 = 'ITA'
road_file =  os.path.join(config.INPUT_DIR, 'ITA', config.MOBILITY_DIR,'roads.shp')
roadGDF = gpd.read_file(road_file)
save_path = os.path.join(config.INPUT_DIR, 'BRA', config.MOBILITY_DIR,'hotosm_bra_east_roads_gpkg.zip!hotosm_bra_east_roads.gpkg')
braGDF =  gpd.read_file(f'zip://{save_path}')

/home/jaredross/work/testModels/pa-COVID-model-parameterization/venv/lib/python3.7/site-packages/geopandas/geodataframe.py:422: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
  for feature in features_lst:

In [11]:
roadGDF

,osm_id,name,ref,type,oneway,maxspeed,geometry
0,1784572,Autodromo Santamonica,None,unclassified,1,0,"LINESTRING (12.68509 43.96365, 12.68494 43.963..."
1,2132461,Via Alcide Degasperi,None,tertiary,0,0,"LINESTRING (11.11861 46.05249, 11.11889 46.052..."
2,2132466,Autostrada del Brennero - Brennerautobahn,A22,motorway,1,110,"LINESTRING (11.37858 46.49328, 11.37897 46.493..."
3,2132469,None,None,secondary,0,0,"LINESTRING (9.72835 44.47119, 9.72854 44.47117..."
4,2132473,None,None,secondary,0,0,"LINESTRING (9.69071 44.48749, 9.69168 44.48734..."
...,...,...,...,...,...,...,...
308682,37418347,None,None,service,1,0,"LINESTRING (12.41453 42.77963, 12.41464 42.779..."
308683,37418462,None,None,path,0,0,"LINESTRING (7.66712 43.98935, 7.66736 43.98950..."
308684,37418499,None,None,steps,0,0,"LINESTRING (12.41487 42.77950, 12.41495 42.77957)"
308685,37418500,None,None,service,0,0,"LINESTRING (12.41483 42.77961, 12.41495 42.779..."
308686,37419340,None,None,path,0,0,"LINESTRING (11.14612 46.03616, 11.14557 46.03610)"

In [12]:
braGDF

,osm_id,layer,oneway,source,bridge,name,surface,width,lanes,highway,smoothness,geometry
0,4327285,None,yes,None,None,Rodovia Fernão Dias,paved,None,2,motorway,None,"LINESTRING (-46.37287 -22.87927, -46.37323 -22..."
1,4350143,None,None,None,None,Avenida Jorge Teixeira,None,None,2,secondary,None,"LINESTRING (-40.83168 -14.85910, -40.83080 -14..."
2,4350146,None,yes,None,None,Avenida Rosa Cruz,None,None,None,tertiary,None,"LINESTRING (-40.82403 -14.85383, -40.82403 -14..."
3,4351605,None,None,None,None,Avenida Espanha,None,None,None,residential,None,"LINESTRING (-40.82299 -14.85451, -40.82306 -14..."
4,4351607,None,yes,None,None,Avenida Olívia Flores,None,None,2,primary,None,"LINESTRING (-40.81904 -14.87187, -40.81933 -14..."
...,...,...,...,...,...,...,...,...,...,...,...,...
1363263,866282567,None,None,None,None,None,None,None,None,service,None,"LINESTRING (-43.60952 -21.30105, -43.60944 -21..."
1363264,866282568,None,None,None,None,None,None,None,None,unclassified,None,"LINESTRING (-43.61909 -21.28160, -43.61884 -21..."
1363265,866282569,None,None,None,None,None,None,None,None,unclassified,None,"LINESTRING (-43.57465 -21.29897, -43.57441 -21..."
1363266,866284296,None,None,None,None,None,None,None,None,residential,None,"LINESTRING (-43.66896 -19.89130, -43.66865 -19..."
1363267,866284297,None,None,None,None,None,None,None,None,residential,None,"LINESTRING (-43.66989 -19.89072, -43.66970 -19..."

In [18]:
import logging
logger = logging.getLogger(__name__)

def load_adm(country_iso3, config, parameters, level=2):
    logger.info(f'Reading in admin {level} file')
    df_adm = utils.read_in_admin_boundaries(config, parameters, country_iso3)
    # Modify admin 2 files to contain admin 1 name
    df_adm.loc[:, 'ADM'] = df_adm[f'ADM{level}_PCODE']
    df_adm = df_adm.sort_values(by='ADM').reset_index(drop=True)
    return df_adm

def get_borders(df_adm):
    df_borders = df_adm.copy()
    df_borders['geometry'] = df_borders['geometry'].boundary
    return df_borders

In [22]:
df_adm = load_adm(country_iso3, config, parameters)
df_adm = df_adm.to_crs("EPSG:4326")
df_borders = get_borders(df_adm)
df_adm

{'admin': {'directory': 'ProvCM01012020', 'language': 'IT', 'references': ['Reg01012020', 'RipGeo01012020'], 'adm_renames': {'COD_RIP': 'ADM0_PCODE', 'COD_REG': 'ADM1_PCODE', 'COD_PROV': 'ADM2_PCODE', 'DEN_UTS': 'ADM2_IT', 'DEN_REG': 'ADM1_IT', 'DEN_RIP': 'ADM0_IT'}}, 'mobility': {'scaling_factor': {'household_size': 2.4, 'motor_vehicle_fraction': 0.734}}, 'vulnerability': {'ghs': {'column_row_pairs': ['(18, 3)', '(18, 4)', '(19, 3)', '(19, 4)']}, 'ipc': {'filename': None}, 'solid_fuels': {'frac_urban': 0.02, 'frac_rural': 0.02}, 'handwashing_facilities': {'frac_urban': 0.05, 'frac_rural': 0.1}, 'raised_blood_pressure': 0.38, 'diabetes': 0.053, 'smoking': 0.19}, 'covid': {'url': 'https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json', 'filename': 'dpc-covid19-ita-regioni.json', 'filtype': 'json', 'header': 0, 'skiprows': 0, 'cases': None, 'deaths': None, 'individual_case_data': None, 'cumulative': None, 'admin_level': None, 'federal_state_dict': None, 'adm1_name_exp': None, 'adm2_name_exp': None, 'date_format': None, 'replace_dict': {'old_name': None}, 'hlx_dict': {'#old_hxl_name': None}}, 'contact_matrix': {'country': 'Italy', 'file_number': 1}, 'NPIs': {'url': None}}
ITA

,ADM0_PCODE,ADM1_PCODE,ADM2_PCODE,COD_CM,COD_UTS,DEN_PROV,DEN_CM,ADM2_IT,SIGLA,TIPO_UTS,SHAPE_AREA,SHAPE_LEN,geometry,ADM1_IT,ADM0_IT,ADM
0,1,1,1,201,201,-,Torino,Torino,TO,Citta metropolitana,6.826908e+09,593389.667001,"POLYGON ((7.85904 45.59758, 7.85976 45.59723, ...",Piemonte,Nord-Ovest,1
1,1,1,2,0,2,Vercelli,-,Vercelli,VC,Provincia,2.081602e+09,458754.449021,"POLYGON ((8.19874 45.94993, 8.19893 45.94988, ...",Piemonte,Nord-Ovest,2
2,1,1,3,0,3,Novara,-,Novara,NO,Provincia,1.340250e+09,276722.284585,"POLYGON ((8.47365 45.86742, 8.47410 45.86716, ...",Piemonte,Nord-Ovest,3
3,1,1,4,0,4,Cuneo,-,Cuneo,CN,Provincia,6.894828e+09,542063.983810,"MULTIPOLYGON (((7.97088 44.85254, 7.97135 44.8...",Piemonte,Nord-Ovest,4
4,1,1,5,0,5,Asti,-,Asti,AT,Provincia,1.510170e+09,356521.052241,"POLYGON ((8.02884 45.13272, 8.02895 45.13270, ...",Piemonte,Nord-Ovest,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,1,1,103,0,103,Verbano-Cusio-Ossola,-,Verbano-Cusio-Ossola,VB,Provincia,2.260887e+09,316521.773202,"POLYGON ((8.43834 46.46410, 8.43841 46.46378, ...",Piemonte,Nord-Ovest,103
103,1,3,108,0,108,Monza e della Brianza,-,Monza e della Brianza,MB,Provincia,4.054079e+08,164691.454327,"POLYGON ((9.25306 45.74071, 9.25394 45.74046, ...",Lombardia,Nord-Ovest,108
104,3,11,109,0,109,Fermo,-,Fermo,FM,Provincia,8.627532e+08,226568.225869,"POLYGON ((13.74617 43.28889, 13.74763 43.28614...",Marche,Centro,109
105,4,16,110,0,110,Barletta-Andria-Trani,-,Barletta-Andria-Trani,BT,Provincia,1.542926e+09,275814.149356,"POLYGON ((15.95552 41.44029, 15.95745 41.44014...",Puglia,Sud,110
106,5,20,111,0,111,Sud Sardegna,-,Sud Sardegna,SU,Provincia,6.530673e+09,900961.615952,"MULTIPOLYGON (((8.36424 39.03288, 8.36431 39.0...",Sardegna,Isole,111

In [26]:
roadGDF

,osm_id,name,ref,type,oneway,maxspeed,geometry
0,1784572,Autodromo Santamonica,None,unclassified,1,0,"LINESTRING (12.68509 43.96365, 12.68494 43.963..."
1,2132461,Via Alcide Degasperi,None,tertiary,0,0,"LINESTRING (11.11861 46.05249, 11.11889 46.052..."
2,2132466,Autostrada del Brennero - Brennerautobahn,A22,motorway,1,110,"LINESTRING (11.37858 46.49328, 11.37897 46.493..."
3,2132469,None,None,secondary,0,0,"LINESTRING (9.72835 44.47119, 9.72854 44.47117..."
4,2132473,None,None,secondary,0,0,"LINESTRING (9.69071 44.48749, 9.69168 44.48734..."
...,...,...,...,...,...,...,...
308682,37418347,None,None,service,1,0,"LINESTRING (12.41453 42.77963, 12.41464 42.779..."
308683,37418462,None,None,path,0,0,"LINESTRING (7.66712 43.98935, 7.66736 43.98950..."
308684,37418499,None,None,steps,0,0,"LINESTRING (12.41487 42.77950, 12.41495 42.77957)"
308685,37418500,None,None,service,0,0,"LINESTRING (12.41483 42.77961, 12.41495 42.779..."
308686,37419340,None,None,path,0,0,"LINESTRING (11.14612 46.03616, 11.14557 46.03610)"

In [25]:
%%time
intersect = gpd.overlay(roadGDF, df_adm, how='intersection')
intersect

CPU times: user 27min 48s, sys: 320 ms, total: 27min 48s
Wall time: 27min 48s

,osm_id,name,ref,type,oneway,maxspeed,ADM0_PCODE,ADM1_PCODE,ADM2_PCODE,COD_CM,...,DEN_CM,ADM2_IT,SIGLA,TIPO_UTS,SHAPE_AREA,SHAPE_LEN,ADM1_IT,ADM0_IT,ADM,geometry
0,1784572,Autodromo Santamonica,None,unclassified,1,0,2,8,99,0,...,-,Rimini,RN,Provincia,8.650144e+08,288760.194782,Emilia-Romagna,Nord-Est,99,"LINESTRING (12.68509 43.96365, 12.68494 43.963..."
1,10052442,None,None,tertiary,0,0,2,8,99,0,...,-,Rimini,RN,Provincia,8.650144e+08,288760.194782,Emilia-Romagna,Nord-Est,99,"LINESTRING (12.11006 43.77756, 12.11050 43.778..."
2,10052446,None,None,tertiary,0,0,2,8,99,0,...,-,Rimini,RN,Provincia,8.650144e+08,288760.194782,Emilia-Romagna,Nord-Est,99,"LINESTRING (12.17540 43.79978, 12.17515 43.799..."
3,10052470,None,None,tertiary,0,0,2,8,99,0,...,-,Rimini,RN,Provincia,8.650144e+08,288760.194782,Emilia-Romagna,Nord-Est,99,"LINESTRING (12.26523 43.81771, 12.26500 43.817..."
4,11408465,None,SP120,tertiary,0,0,2,8,99,0,...,-,Rimini,RN,Provincia,8.650144e+08,288760.194782,Emilia-Romagna,Nord-Est,99,"LINESTRING (12.38651 43.99057, 12.38629 43.989..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310375,35772436,None,SS 192,secondary,0,0,5,19,86,0,...,-,Enna,EN,Libero consorzio di comuni,2.574666e+09,403941.476001,Sicilia,Isole,86,"LINESTRING (14.36171 37.56284, 14.36319 37.562..."
310376,35772437,None,SS117bis,secondary,0,0,5,19,86,0,...,-,Enna,EN,Libero consorzio di comuni,2.574666e+09,403941.476001,Sicilia,Isole,86,"LINESTRING (14.21658 37.50919, 14.21741 37.507..."
310377,35783080,None,None,tertiary,0,0,5,19,86,0,...,-,Enna,EN,Libero consorzio di comuni,2.574666e+09,403941.476001,Sicilia,Isole,86,"MULTILINESTRING ((14.45508 37.30407, 14.45484 ..."
310378,35795717,None,None,tertiary,0,0,5,19,86,0,...,-,Enna,EN,Libero consorzio di comuni,2.574666e+09,403941.476001,Sicilia,Isole,86,"LINESTRING (14.39122 37.75477, 14.39158 37.755..."
310379,35795718,None,None,secondary,0,0,5,19,86,0,...,-,Enna,EN,Libero consorzio di comuni,2.574666e+09,403941.476001,Sicilia,Isole,86,"LINESTRING (14.39894 37.74848, 14.39903 37.749..."

In [62]:
print(len(intersect['osm_id'].unique()))
intersect

307479

,osm_id,name,ref,type,oneway,maxspeed,ADM0_PCODE,ADM1_PCODE,ADM2_PCODE,COD_CM,...,DEN_CM,ADM2_IT,SIGLA,TIPO_UTS,SHAPE_AREA,SHAPE_LEN,ADM1_IT,ADM0_IT,ADM,geometry
0,1784572,Autodromo Santamonica,None,unclassified,1,0,2,8,99,0,...,-,Rimini,RN,Provincia,8.650144e+08,288760.194782,Emilia-Romagna,Nord-Est,99,"LINESTRING (12.68509 43.96365, 12.68494 43.963..."
1,10052442,None,None,tertiary,0,0,2,8,99,0,...,-,Rimini,RN,Provincia,8.650144e+08,288760.194782,Emilia-Romagna,Nord-Est,99,"LINESTRING (12.11006 43.77756, 12.11050 43.778..."
2,10052446,None,None,tertiary,0,0,2,8,99,0,...,-,Rimini,RN,Provincia,8.650144e+08,288760.194782,Emilia-Romagna,Nord-Est,99,"LINESTRING (12.17540 43.79978, 12.17515 43.799..."
3,10052470,None,None,tertiary,0,0,2,8,99,0,...,-,Rimini,RN,Provincia,8.650144e+08,288760.194782,Emilia-Romagna,Nord-Est,99,"LINESTRING (12.26523 43.81771, 12.26500 43.817..."
4,11408465,None,SP120,tertiary,0,0,2,8,99,0,...,-,Rimini,RN,Provincia,8.650144e+08,288760.194782,Emilia-Romagna,Nord-Est,99,"LINESTRING (12.38651 43.99057, 12.38629 43.989..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310375,35772436,None,SS 192,secondary,0,0,5,19,86,0,...,-,Enna,EN,Libero consorzio di comuni,2.574666e+09,403941.476001,Sicilia,Isole,86,"LINESTRING (14.36171 37.56284, 14.36319 37.562..."
310376,35772437,None,SS117bis,secondary,0,0,5,19,86,0,...,-,Enna,EN,Libero consorzio di comuni,2.574666e+09,403941.476001,Sicilia,Isole,86,"LINESTRING (14.21658 37.50919, 14.21741 37.507..."
310377,35783080,None,None,tertiary,0,0,5,19,86,0,...,-,Enna,EN,Libero consorzio di comuni,2.574666e+09,403941.476001,Sicilia,Isole,86,"MULTILINESTRING ((14.45508 37.30407, 14.45484 ..."
310378,35795717,None,None,tertiary,0,0,5,19,86,0,...,-,Enna,EN,Libero consorzio di comuni,2.574666e+09,403941.476001,Sicilia,Isole,86,"LINESTRING (14.39122 37.75477, 14.39158 37.755..."
310379,35795718,None,None,secondary,0,0,5,19,86,0,...,-,Enna,EN,Libero consorzio di comuni,2.574666e+09,403941.476001,Sicilia,Isole,86,"LINESTRING (14.39894 37.74848, 14.39903 37.749..."

In [133]:
%%time
testIntersect = intersect.copy()
group = testIntersect.groupby('osm_id')['ADM'].apply(list).reset_index(name='crossings')
# testIntersect['crossings'] = group['crossings']
# # testIntersect.loc[testIntersect['crossings'].apply(len) > 1]
# testIntersect['crossings']

testIntersect = group.merge(testIntersect,on='osm_id',how='left')[['osm_id','name','ref','type','oneway','maxspeed','geometry','crossings']]

CPU times: user 6.36 s, sys: 0 ns, total: 6.36 s
Wall time: 6.36 s

,osm_id,name,ref,type,oneway,maxspeed,geometry,crossings
0,1784572,Autodromo Santamonica,None,unclassified,1,0,"LINESTRING (12.68509 43.96365, 12.68494 43.963...",[99]
1,2132461,Via Alcide Degasperi,None,tertiary,0,0,"LINESTRING (11.11861 46.05249, 11.11889 46.052...",[22]
2,2132466,Autostrada del Brennero - Brennerautobahn,A22,motorway,1,110,"LINESTRING (11.37858 46.49328, 11.37897 46.493...",[21]
3,2132469,None,None,secondary,0,0,"LINESTRING (9.72835 44.47119, 9.72854 44.47117...",[34]
4,2132473,None,None,secondary,0,0,"LINESTRING (9.69071 44.48749, 9.69168 44.48734...",[34]
...,...,...,...,...,...,...,...,...
310375,37418347,None,None,service,1,0,"LINESTRING (12.41453 42.77963, 12.41464 42.779...",[54]
310376,37418462,None,None,path,0,0,"LINESTRING (7.66712 43.98935, 7.66736 43.98950...",[8]
310377,37418499,None,None,steps,0,0,"LINESTRING (12.41487 42.77950, 12.41495 42.77957)",[54]
310378,37418500,None,None,service,0,0,"LINESTRING (12.41483 42.77961, 12.41495 42.779...",[54]
310379,37419340,None,None,path,0,0,"LINESTRING (11.14612 46.03616, 11.14557 46.03610)",[22]

In [134]:
import itertools


testIntersect = testIntersect.loc[testIntersect['crossings'].apply(len) > 1]
testIntersect['crossing_pairs'] = testIntersect['crossings'].apply(lambda x:
                                                             list(itertools.combinations(sorted(x), 2)))
testIntersect = testIntersect.drop_duplicates(subset='osm_id')
testIntersect

,osm_id,name,ref,type,oneway,maxspeed,geometry,crossings,crossing_pairs
62,2954434,Raccordo Autostradale Benevento,None,motorway,0,0,"LINESTRING (14.90194 41.06780, 14.90084 41.067...","[62, 64]","[(62, 64)]"
67,2954438,SS Appia,None,primary,0,0,"MULTILINESTRING ((14.65782 41.05474, 14.65798 ...","[62, 64]","[(62, 64)]"
69,2954439,None,None,secondary,0,0,"LINESTRING (14.58222 41.04532, 14.58238 41.045...","[62, 64]","[(62, 64)]"
76,2954474,A16 Napoli Canosa,A16,motorway,0,0,"MULTILINESTRING ((14.81991 40.94118, 14.81855 ...","[64, 63]","[(63, 64)]"
101,3176849,None,None,primary,0,0,"LINESTRING (14.65972 41.39360, 14.65999 41.391...","[62, 70]","[(62, 70)]"
...,...,...,...,...,...,...,...,...,...
309926,37393480,None,None,unclassified,0,0,"MULTILINESTRING ((11.47630 42.43749, 11.47633 ...","[53, 56]","[(53, 56)]"
309928,37393481,None,None,unclassified,0,0,"LINESTRING (11.51653 42.44914, 11.51636 42.448...","[53, 56]","[(53, 56)]"
309936,37393488,Strada Provinciale 67 di Campigliola,SP67,tertiary,0,0,"LINESTRING (11.61241 42.43679, 11.61155 42.437...","[53, 56]","[(53, 56)]"
309983,37407146,None,None,tertiary,0,0,"LINESTRING (12.87979 45.82501, 12.88023 45.824...","[27, 93]","[(27, 93)]"
310148,37412246,None,SS 188,primary,0,0,"MULTILINESTRING ((13.21407 37.66751, 13.21423 ...","[82, 84]","[(82, 84)]"

df_roads = gpd.read_file(road_file)

In [29]:
%%time
# For each road, get provinces that it intersects with
# !!! This takes awhile to run
df_roads['crossings'] = df_roads['geometry'].apply(lambda x:
                                                   [y['ADM']
                                                    for _, y in df_adm.iterrows()
                                                    if x.intersects(y['geometry'])
                                                    ])

df_roads

CPU times: user 55min 56s, sys: 1.51 s, total: 55min 57s
Wall time: 55min 54s

,osm_id,name,ref,type,oneway,maxspeed,geometry,crossings
0,1784572,Autodromo Santamonica,None,unclassified,1,0,"LINESTRING (12.68509 43.96365, 12.68494 43.963...",[99]
1,2132461,Via Alcide Degasperi,None,tertiary,0,0,"LINESTRING (11.11861 46.05249, 11.11889 46.052...",[22]
2,2132466,Autostrada del Brennero - Brennerautobahn,A22,motorway,1,110,"LINESTRING (11.37858 46.49328, 11.37897 46.493...",[21]
3,2132469,None,None,secondary,0,0,"LINESTRING (9.72835 44.47119, 9.72854 44.47117...",[34]
4,2132473,None,None,secondary,0,0,"LINESTRING (9.69071 44.48749, 9.69168 44.48734...",[34]
...,...,...,...,...,...,...,...,...
308682,37418347,None,None,service,1,0,"LINESTRING (12.41453 42.77963, 12.41464 42.779...",[54]
308683,37418462,None,None,path,0,0,"LINESTRING (7.66712 43.98935, 7.66736 43.98950...",[8]
308684,37418499,None,None,steps,0,0,"LINESTRING (12.41487 42.77950, 12.41495 42.77957)",[54]
308685,37418500,None,None,service,0,0,"LINESTRING (12.41483 42.77961, 12.41495 42.779...",[54]
308686,37419340,None,None,path,0,0,"LINESTRING (11.14612 46.03616, 11.14557 46.03610)",[22]

In [35]:
df_roads = df_roads.loc[df_roads['crossings'].apply(len) > 1]
len(df_roads['osm_id'].unique())

2828

In [91]:
df_roads['crossing_pairs'] = df_roads['crossings'].apply(lambda x:
                                                             list(itertools.combinations(sorted(x), 2)))
df_roads

,osm_id,name,ref,type,oneway,maxspeed,geometry,crossings,crossing_pairs
62,2954434,Raccordo Autostradale Benevento,None,motorway,0,0,"LINESTRING (14.91543 41.06781, 14.91396 41.068...","[62, 64]","[(62, 64)]"
66,2954438,SS Appia,None,primary,0,0,"LINESTRING (14.65782 41.05474, 14.65798 41.054...","[62, 64]","[(62, 64)]"
67,2954439,None,None,secondary,0,0,"LINESTRING (14.58222 41.04532, 14.58238 41.045...","[62, 64]","[(62, 64)]"
73,2954474,A16 Napoli Canosa,A16,motorway,0,0,"LINESTRING (14.81991 40.94118, 14.81855 40.940...","[63, 64]","[(63, 64)]"
97,3176849,None,None,primary,0,0,"LINESTRING (14.55790 41.46345, 14.55778 41.463...","[62, 70]","[(62, 70)]"
...,...,...,...,...,...,...,...,...,...
308231,37393480,None,None,unclassified,0,0,"LINESTRING (11.47630 42.43749, 11.47633 42.437...","[53, 56]","[(53, 56)]"
308232,37393481,None,None,unclassified,0,0,"LINESTRING (11.51653 42.44914, 11.51636 42.448...","[53, 56]","[(53, 56)]"
308239,37393488,Strada Provinciale 67 di Campigliola,SP67,tertiary,0,0,"LINESTRING (11.62415 42.43141, 11.62170 42.431...","[53, 56]","[(53, 56)]"
308285,37407146,None,None,tertiary,0,0,"LINESTRING (12.87919 45.82589, 12.87956 45.825...","[27, 93]","[(27, 93)]"
308449,37412246,None,SS 188,primary,0,0,"LINESTRING (13.02925 37.64650, 13.03020 37.645...","[82, 84]","[(82, 84)]"

In [113]:
len(list(set(list(testIntersect['osm_id']))-set(list(df_roads['osm_id']))))

0

In [138]:
df_roads[df_roads['osm_id']==2954474]

,osm_id,name,ref,type,oneway,maxspeed,geometry,crossings,crossing_pairs
73,2954474,A16 Napoli Canosa,A16,motorway,0,0,"LINESTRING (14.81991 40.94118, 14.81855 40.940...","[63, 64]","[(63, 64)]"

In [139]:
testIntersect[testIntersect['osm_id']==2954474]

,osm_id,name,ref,type,oneway,maxspeed,geometry,crossings,crossing_pairs
76,2954474,A16 Napoli Canosa,A16,motorway,0,0,"MULTILINESTRING ((14.81991 40.94118, 14.81855 ...","[64, 63]","[(63, 64)]"

In [11]:
%%time
from covid_model_parametrization.config import Config

config = Config()
parameters = config.parameters("ita")
df_covid = pd.read_csv('Inputs/ITA/COVID/dpc-covid19-ita-regioni.csv',header=0,skiprows=0)
df_covid=df_covid.drop_duplicates()
df_covid=df_covid.drop_duplicates()
df_covid = df_covid.rename(columns=parameters["covid"]["hlx_dict"])


df_covid[df_covid["#adm1+pcode"].isin([9,10,11,12,13])]

CPU times: user 41.1 ms, sys: 223 µs, total: 41.3 ms
Wall time: 38.7 ms

,#date,stato,#adm1+pcode,#adm1+name,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,...,#affected+infected+dead+total,casi_da_sospetto_diagnostico,casi_da_screening,#affected+infected+confirmed+total,tamponi,casi_testati,note,ingressi_terapia_intensiva,note_test,note_casi
0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,...,0,NaN,NaN,0,5,NaN,NaN,NaN,NaN,NaN
6,2020-02-24T18:00:00,ITA,12,Lazio,41.892770,12.483667,1,1,2,0,...,0,NaN,NaN,3,124,NaN,NaN,NaN,NaN,NaN
9,2020-02-24T18:00:00,ITA,11,Marche,43.616760,13.518875,0,0,0,0,...,0,NaN,NaN,0,16,NaN,NaN,NaN,NaN,NaN
17,2020-02-24T18:00:00,ITA,9,Toscana,43.769231,11.255889,0,0,0,0,...,0,NaN,NaN,0,140,NaN,NaN,NaN,NaN,NaN
18,2020-02-24T18:00:00,ITA,10,Umbria,43.106758,12.388247,0,0,0,0,...,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6090,2020-12-10T17:00:00,ITA,13,Abruzzo,42.351222,13.398438,657,65,722,15269,...,1013,NaN,NaN,31201,449788,250253.0,NaN,6.0,NaN,NaN
6096,2020-12-10T17:00:00,ITA,12,Lazio,41.892770,12.483667,3036,339,3375,87392,...,2802,NaN,NaN,135913,2414442,1912167.0,NaN,19.0,NaN,NaN
6099,2020-12-10T17:00:00,ITA,11,Marche,43.616760,13.518875,501,86,587,12632,...,1373,NaN,NaN,33383,443307,259267.0,NaN,5.0,NaN,NaN
6107,2020-12-10T17:00:00,ITA,9,Toscana,43.769231,11.255889,1323,247,1570,20762,...,3032,NaN,NaN,110440,1680849,993998.0,NaN,11.0,Positivi diagnosticati solo con test antigenic...,NaN
6108,2020-12-10T17:00:00,ITA,10,Umbria,43.106758,12.388247,310,55,365,5014,...,498,NaN,NaN,25615,447196,234249.0,NaN,5.0,NaN,NaN

In [9]:
df_covid[df_covid["#adm1+pcode"].isin([9,10,11,12,13])].to_csv('ITA_covid.csv')